[tool.poetry]
name = "python-study-group"
version = "0.1.0"
description = ""
authors = ["Zuriel Diaz <zuriel_diaz@epam.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pytest = "^8.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
